version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "18880:80"
    volumes:
      - ./docker.nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - ./docker.php.ini-development:/usr/local/etc/php/php.ini-development
      - ./docker.php.ini-production:/usr/local/etc/php/php.ini-production
      - ./docker.php.ini-production:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "18000:8000"
    volumes:
      - ./configs:/cfgs
      - .:/var/www/html
    env_file: .env

  mariadb:
    image: mariadb:latest
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: creaf12345 
      MYSQL_DATABASE: bride_db          
      MYSQL_USER: creaftech            
      MYSQL_PASSWORD: creaf12345        
    ports:
      - "3306:3306"                        

  redis:
    image: redis:latest
    hostname: redis
    command: ["redis-server", "--requirepass", "redis_password"]
    environment:
      REDIS_PASSWORD: redis_password
